cargo-features = ["edition2024"]

[package]
name = "native-contract"
version = "0.1.0"
edition = "2024"

[lib]
crate-type=["cdylib", "lib"]

[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-program = "2.3.0"
solana-program-entrypoint = "2.3.0"
